title: VishDaily Blog
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  my daily stuff 

# Build settings
markdown: kramdown
#theme: jekyll-theme-midnight
theme: jekyll-theme-hacker
#theme: jekyll-theme-cayman

plugins:
 - jekyll-feed

# Include _pages directory and its contents
include: ['_pages']
